### ISSUE TITLE
Using private symbol _CFExecutableLinkedOnOrAfter 

### ISSUE THREAD

**Issue by sreilly** [violetlib/jnr#1]
Is there a substitute for the use of _CFExecutableLinkedOnOrAfter in the code within `org_violetlib_jnr_aqua_impl_AquaNativePainter.m`? Apps submitted to the mac app store are rejected because of it. Would it be possible to use `MAC_OS_X_VERSION_MAX_ALLOWED` instead?

**Comment by cbfiddle** [comment]
I would assume so. Can you suggest the replacement code?

**Comment by sreilly** [comment]
I'd be happy to. Can you confirm though that the code is meant to determine the SDK version that was used to compile the software and not the runtime version in which the code's being used?

**Comment by cbfiddle** [comment]
Not without some investigation, so it would be nice if you could figure it out.

**Comment by cbfiddle** [comment]
I should add that the goal is for the code to run on Yosemite and later. It does not have to compile on older releases.

**Comment by cbfiddle** [comment]
Fixed in Release 12. Thank you.
