### ISSUE TITLE
Missing file building current main branch

### ISSUE THREAD

**Issue by rwcope2** [violetlib/jnr#7]
I pulled the current main branch (as of 2024-03-11), and when I try to build it I get the following error:

```
...violetlib/jnr/jni/org_violetlib_jnr_aqua_impl_AquaUIPainterBase.m:10:10: fatal error: 'org_violetlib_jnr_aqua_impl_AquaUIPainterBase.h' file not found
#include "org_violetlib_jnr_aqua_impl_AquaUIPainterBase.h"
```
I don't see org_violetlib_jnr_aqua_impl_AquaUIPainterBase.h in the project anywhere.  Is that supposed to be coming from somewhere else?

Thanks,  
Rob

**Comment by cbfiddle** [comment]
That file is generated by javac.

**Comment by rwcope2** [comment]
Got it, thanks.  I was running the build script from the wrong directory.
