### ISSUE TITLE
Typo in current build-common.xml?

### ISSUE THREAD

**Issue by rwcope2** [violetlib/jnr#8]
Line 12 of build-common.xml is `<property name="RELEASE" value="4"/>`.  The current VAqua build specifies version 14 of JNR, and based on previous versions, I believe the value should be 14 instead of 4.

BTW, I did build the latest VAqua.  On an M1 Mac with aarm64 versions of Java 11 and Java 17, everything I have tested has worked flawlessly. Thank you!

I also like VBuilder.  It really simplifies the build.  Nice work!

**Comment by cbfiddle** [comment]
Thanks for the report. I have updated the script.

You might guess that I always override this property when I build… :-)

**Comment by cbfiddle** [comment]
Not sure if you noticed, but you can use it to build universal applications.

**Comment by rwcope2** [comment]
> Not sure if you noticed, but you can use it to build universal applications.

Thanks, yes I did notice that, and it got us thinking about using it.  The increased size of the application might be worth the simplified download.

**Comment by cbfiddle** [comment]
If you are brave, you might try sharing the lib/modules file, which would save on the order of 100 MB.
